server:
  port: 8084

droplets:
  notifications:
    expiryTime: 60000
    otpSize: 6

spring:
  application:
    name: droplets-notification-ms
  mail:
    host: smtp.gmail.com
    port: 587
    username: FAKE
    password: FAKE
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          from: FAKE
          starttls:
            enable: true
  main:
    allow-bean-definition-overriding: true
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        temp:
          use_jdbc_metadata_defaults: false
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/droplets
    username: postgres
    password: charlie
    driver: org.postgresql.Driver